const wordsBasic = [
  { id: 1, word: 'Happy', synonym: ['Joyful', 'Cheerful'] },
  { id: 2, word: 'Joyful', synonym: ['Happy', 'Cheerful'] },
  { id: 3, word: 'Cheerful', synonym: ['Joyful', 'Happy'] },
  { id: 4, word: 'Fast', synonym: ['Quick', 'Speedy'] },
  { id: 5, word: 'Quick', synonym: ['Fast', 'Speedy'] },
  { id: 6, word: 'Speedy', synonym: ['Quick','Fast'] },
  { id: 7, word: 'Smart', synonym: ['Clever', 'Bright'] },
  { id: 8, word: 'Clever', synonym: ['Smart', 'Bright'] },
  { id: 9, word: 'Bright', synonym: ['Clever','Smart'] },
  { id: 10, word: 'Angry', synonym: ['Furious', 'Enraged'] },
  { id: 11, word: 'Furious', synonym: ['Angry', 'Enraged'] },
  { id: 12, word: 'Enraged', synonym: ['Furious', 'Angry'] },
  { id: 13, word: 'Beautiful', synonym: ['Gorgeous', 'Attractive'] },
  { id: 14, word: 'Gorgeous', synonym: ['Beautiful', 'Attractive'] },
  { id: 15, word: 'Attractive', synonym: ['Gorgeous', 'Beautiful'] },
  { id: 16, word: 'Strong', synonym: ['Powerful', 'Tough'] },
  { id: 17, word: 'Powerful', synonym: ['Strong', 'Tough'] },
  { id: 18, word: 'Tough', synonym: ['Powerful', 'Strong'] },
  { id: 19, word: 'Brave', synonym: ['Courageous', 'Fearless'] },
  { id: 20, word: 'Courageous', synonym: ['Brave', 'Fearless'] },
  { id: 21, word: 'Fearless', synonym: ['Courageous', 'Brave'] },
  { id: 22, word: 'Calm', synonym: ['Peaceful', 'Tranquil'] },
  { id: 23, word: 'Peaceful', synonym: ['Calm', 'Tranquil'] },
  { id: 24, word: 'Tranquil', synonym: ['Peaceful', 'Calm'] },
];

module.exports = wordsBasic;
